image_types_reach.bbclass: inherit image_types
That's required for 'imagetypes_getdepends'.  Fixes:

Exception: NameError: global name 'imagetypes_getdepends' is not defined

Signed-off-by: Mario Domenech Goulart <mario@ossystems.com.br>