g2s-101-24: fix firmware package names
Replace firmware-imx-ar3k by linux-firmware-ar3k and firmware-imx-ath6
by linux-firwmare-ath6.

Fixes:

ERROR: Nothing RPROVIDES 'firmware-imx-ar3k'
  (but /home/mario/src/reach/sources/poky/meta/recipes-core/packagegroups/packagegroup-base.bb
  RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'firmware-imx-ar3k' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['firmware-imx-ar3k']
NOTE: Runtime target 'packagegroup-base-extended' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-base-extended',
  'firmware-imx-ar3k']
ERROR: Required build target 'reach-image-minimal' has no buildable providers.
Missing or unbuildable dependency chain was: ['reach-image-minimal',
  'packagegroup-base-extended', 'firmware-imx-ar3k']

Signed-off-by: Mario Domenech Goulart <mario@ossystems.com.br>